#!/usr/bin/env bashio
# shellcheck shell=bash
set -e

##############
# Initialize #
##############

CONFIG_HOME="$(bashio::config "CONFIG_LOCATION")"
CONFIG_HOME="$(dirname "$CONFIG_HOME")"

# Config.env is now generated in 30-generate-config.sh from addon settings
if [ ! -f "$CONFIG_HOME/config.env" ]; then
    bashio::log.error "config.env not found! This should have been generated by 30-generate-config.sh"
    exit 1
fi

bashio::log.info "Using config.env from $CONFIG_HOME"

# Remove erroneous folder named config.env (bug fix for looping issue)
if [ -d "$CONFIG_HOME/config.env" ]; then
    bashio::log.warning "Found directory named config.env, deleting it..."
    rm -rf "$CONFIG_HOME/config.env"                   # Fix: Ensures directory removal even if it exists
    cp /templates/config.env "$CONFIG_HOME/config.env" # Recreate as a valid file
    chmod 755 "$CONFIG_HOME/config.env"
fi

# Copy new file
mkdir -p /data/data
cp "$CONFIG_HOME/config.env" /data/data/

# Permissions
chmod -R 755 "$CONFIG_HOME"

# Export variables
set -a
echo ""
bashio::log.info "Sourcing variables from $CONFIG_HOME/config.env"
cp "$CONFIG_HOME"/config.env /config.env
# Remove previous instance
sed -i "s|export ||g" /config.env
# Add export for non empty lines
sed -i '/\S/s/^/export /' /config.env
# Delete lines starting with #
sed -i '/export #/d' /config.env
# Get variables
# shellcheck source=/dev/null
source /config.env
rm /config.env
set +a

##############
# Launch App #
##############

# Go to folder
cd /data || true

# Fetch commands
CMD_ARGUMENTS="$(bashio::config "CMD_ARGUMENTS")"
IFS=';'
read -ar strarr <<< "$CMD_ARGUMENTS"

# Sanitizes commands
trim() {
    local var="$*"
    var="${var#"${var%%[![:space:]]*}"}"
    var="${var%"${var##*[![:space:]]}"}"
    printf '%s' "$var"
}

# Add docker-entrypoint command
for val in "${strarr[@]}"; do
    val="$(trim "$val")"
    echo " "
    bashio::log.info "Starting the app with arguments \"$val\""
    echo " "
    echo "$val" | xargs docker-entrypoint.sh || true
done


##############
# Launch ASF #
##############

bashio::log.info "Starting ArchiSteamFarm (ASF)..."

# Navigate to ASF directory
cd /data/asf || true


# --- FORCE ASF CONFIG (Fixes Update Loop) ---
ASF_CONFIG="/data/asf/config/ASF.json"
if [ -f "$ASF_CONFIG" ]; then
    bashio::log.info "ASF.json exists. Enforcing UpdatePeriod: 0 via modification."
    # Use sed to replace UpdatePeriod value or insert it if missing (simplified approach)
    # Check if UpdatePeriod exists
    if grep -q "UpdatePeriod" "$ASF_CONFIG"; then
        sed -i -E 's/"UpdatePeriod"\s*:\s*[0-9]+/"UpdatePeriod": 0/' "$ASF_CONFIG"
    else
        # Insert after opening brace (risky if brace not on first line, but standard ASF config usually starts with {)
        sed -i 's/{/{"UpdatePeriod": 0,/' "$ASF_CONFIG"
    fi
else
    bashio::log.info "ASF.json missing. Creating default with UpdatePeriod: 0."
    cat > "$ASF_CONFIG" <<EOF
{
  "IPC": true,
  "UpdateChannel": 0,
  "UpdatePeriod": 0,
  "Headless": true
}
EOF
fi

# --- CHECK STEAM BOT CONFIG (Restores Bot Functionality) ---
BOT_CONFIG="/data/asf/config/SteamBot.json"
STEAM_LOGIN="$(bashio::config "steam_username" || echo "")"
STEAM_PASSWORD="$(bashio::config "steam_password" || echo "")"

if [ -f "$BOT_CONFIG" ]; then
    bashio::log.info "SteamBot.json exists. Using existing configuration (Preserving DB)."
elif [ -n "$STEAM_LOGIN" ] && [ "$STEAM_LOGIN" != "null" ]; then
    bashio::log.info "SteamBot.json missing. Generating from add-on settings for user: $STEAM_LOGIN"
    cat > "$BOT_CONFIG" <<EOF
{
  "SteamLogin": "$STEAM_LOGIN",
  "SteamPassword": "$STEAM_PASSWORD",
  "Enabled": true,
  "FarmingPreferences": 0
}
EOF
else
    bashio::log.warning "No Steam credentials found and no existing SteamBot.json! Bot will not start."
fi


# --- IMPORT STEAM DB (Fixes 2FA) ---
if [ -f "/SteamBot.db" ]; then
    bashio::log.info "Found SteamBot.db in image. Installing to ASF config..."
    cp /SteamBot.db /data/asf/config/SteamBot.db
    # Ensure correct permissions if needed, though ASF runs as root usually in this container
fi

# Start ASF in background
./ArchiSteamFarm &
PID=$!

bashio::log.info "ASF started with PID $PID"
bashio::log.info "Waiting for ASF process ($PID) to finish..."

# Wait for ASF
wait $PID

bashio::log.info "ASF process exited."
bashio::log.info "All actions concluded. Stopping addon."
bashio::addon.stop

